# Chapter 5 - Introduction to _numpy_, *pandas*, and _matplotlib_

Numpy library is more efficient than lists, making it faster and using up less memory. Pandas helps organizes data in tables using numpy. 

# Arrays

Lists are less efficient but are useful if you need values to be changing over time. Numpy creates arrays that contain data types that are values (Integers and variety of floats). This increases efficiency. 

In [5]:
# Created an array
import numpy as np
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [6]:
# Seeing what type the array is
type(array)

numpy.ndarray

In [8]:
# Printing the values and types
for val in array:
    print(val, type(val))

1 <class 'numpy.int32'>
2 <class 'numpy.int32'>
3 <class 'numpy.int32'>
4 <class 'numpy.int32'>
5 <class 'numpy.int32'>


# np.arange(start, finish, interval)

In [11]:
# Passing a range instead of a list
range_array = np.arange(0,101)
range_array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [15]:
# Range counting by 3
range_array = np.arange(0,101, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [36]:
# Range counting backwards by 3
# arange = array range
range_array = np.arange(101,0, -3)
range_array

array([101,  98,  95,  92,  89,  86,  83,  80,  77,  74,  71,  68,  65,
        62,  59,  56,  53,  50,  47,  44,  41,  38,  35,  32,  29,  26,
        23,  20,  17,  14,  11,   8,   5,   2])

# Forming an array with a list of different types of values

In [35]:
# Has one value that is not an int
int_float_list = [1,2,3,4.,5]
print("int_float_list")
for val in int_float_list:
    print(val, type(val))

# All values are changed to float 64 type
mystery_array = np.array(int_float_list)  
print() 
print("mystery_array")
for val in mystery_array:
    print(val, type(val))

# Has all values as float 64 type
float_list = [1.,2.,3.,4.,5.]
float_array = np.array(float_list)
print()
print("float_array")
for val in float_array:
    print(val, type(val))

int_float_list
1 <class 'int'>
2 <class 'int'>
3 <class 'int'>
4.0 <class 'float'>
5 <class 'int'>

mystery_array
1.0 <class 'numpy.float64'>
2.0 <class 'numpy.float64'>
3.0 <class 'numpy.float64'>
4.0 <class 'numpy.float64'>
5.0 <class 'numpy.float64'>

float_array
1.0 <class 'numpy.float64'>
2.0 <class 'numpy.float64'>
3.0 <class 'numpy.float64'>
4.0 <class 'numpy.float64'>
5.0 <class 'numpy.float64'>


In last case (float_array), we check to see if the transfomration of a list of all floats is the same as the transformation of a mixed list of floats and ints (int_float_list).

# Two dimensional lists and arrays

In [46]:
# two_dim_list = A list of lists
# Keep the lists the same for ease of use
two_dim_list = [[1,2,3], [2, 4, 6], [3, 6, 9]]
two_dim_list

[[1, 2, 3], [2, 4, 6], [3, 6, 9]]

In [41]:
# Prints lists of the two_dim_list
for lst in two_dim_list:
    print(lst)
# To print out each value in each list
    for val in lst:
        print(val)

[1, 2, 3]
1
2
3
[2, 4, 6]
2
4
6
[3, 6, 9]
3
6
9


## Transform two dimensional list to two dimensional array using np.array(lst)

In [43]:
two_dim_array = np.array(two_dim_list)
two_dim_array

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [45]:
# Prints the same as the list previously
for array in two_dim_array:
    print(array)
    for val in array:
        print(val)

[1 2 3]
1
2
3
[2 4 6]
2
4
6
[3 6 9]
3
6
9


## Changing the values of elements in an array

Use a list if you simply need to add another element and use an array if you are going to change a value.

In [51]:
# Uses built in array of zeros - Can for example add an extra 3 for a third dimension
array = np.zeros((3,3))
array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
# Changes values at each
array[0][0] = 1
array[1][1] = 3
array[2][2] = 2
array

array([[1., 0., 0.],
       [0., 3., 0.],
       [0., 0., 2.]])

np.zeros creates an n-dimensional array (array of arrays) that is comprised of zeros that are floats. 

If an n-dimensional array of zeros that are ints is desired, create an n-dimensional list using zeros that are integers

In [66]:
# Prints an array of integers intead of the default floats in an array
zero_lst_of_lsts = [[0,0,0],[0,0,0],[0,0,0]]
zero_array_of_arrays = np.array(zero_lst_of_lsts)
zero_array_of_arrays

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [63]:
zero_array_of_arrays[0][0] = 4
zero_array_of_arrays

array([[4, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [65]:
# Another way to complete the previous output
np.zeros((3,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Logging Data

In [68]:
# Log of natural number
import numpy as np

np.log(np.e)

1.0

In [69]:
# Gives the same since log to the 1 gives you 10, etc
np.log10(10)

1.0

In [70]:
np.log10(100)

2.0

In [74]:
# Increases by a decreasing rate 
for i in range(10, 1001, 10):
    print(i, np.log10(i))

10 1.0
20 1.3010299956639813
30 1.4771212547196624
40 1.6020599913279623
50 1.6989700043360187
60 1.7781512503836436
70 1.845098040014257
80 1.9030899869919435
90 1.954242509439325
100 2.0
110 2.041392685158225
120 2.0791812460476247
130 2.113943352306837
140 2.146128035678238
150 2.1760912590556813
160 2.2041199826559246
170 2.230448921378274
180 2.255272505103306
190 2.278753600952829
200 2.3010299956639813
210 2.322219294733919
220 2.342422680822206
230 2.361727836017593
240 2.380211241711606
250 2.3979400086720375
260 2.4149733479708178
270 2.4313637641589874
280 2.4471580313422194
290 2.462397997898956
300 2.4771212547196626
310 2.4913616938342726
320 2.505149978319906
330 2.5185139398778875
340 2.531478917042255
350 2.5440680443502757
360 2.5563025007672873
370 2.568201724066995
380 2.57978359661681
390 2.591064607026499
400 2.6020599913279625
410 2.6127838567197355
420 2.6232492903979003
430 2.6334684555795866
440 2.6434526764861874
450 2.6532125137753435
460 2.662757831681574
4

In [77]:
# Prints out specific values
np.log([1,2,3,4,5])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])